name: pyOFM

on: [push, pull_request]

env:
  REPO_NAME: 'pyofm'
  DOCKER_WORKING_DIR: '/home/dafoamuser/$REPO_NAME'
  DOCKER_MOUNT_DIR: '/home/dafoamuser/mount/$REPO_NAME'
  DOCKER_TAG: 'latest'

jobs:

  regresstion_tests:
    runs-on: ubuntu-22.04
    name: Regression tests
    steps:
    - uses: actions/checkout@main
    - name: Create the docker container and run the tests
      run: |
        docker pull dafoam/opt-packages:${{env.DOCKER_TAG}}
        docker run -i -d -u dafoamuser --name regtest -v $GITHUB_WORKSPACE:${{env.DOCKER_MOUNT_DIR}} dafoam/opt-packages:${{env.DOCKER_TAG}} /bin/bash
        docker exec -i regtest /bin/bash -c "rm -rf ${{ env.DOCKER_WORKING_DIR}} && cp -r ${{env.DOCKER_MOUNT_DIR}} ${{env.DOCKER_WORKING_DIR}}"
        docker exec -i regtest /bin/bash -c ". /home/dafoamuser/dafoam/loadDAFoam.sh && cd ${{env.DOCKER_WORKING_DIR}} && pip install ."
        docker exec -i regtest /bin/bash -c "cd ${{env.DOCKER_WORKING_DIR}}/reg_tests && rm -rf input.tar.gz && wget https://github.com/mdolab/pyofm/raw/main/reg_tests/input.tar.gz && tar -xzf input.tar.gz"
        docker exec -i regtest /bin/bash -c ". /home/dafoamuser/dafoam/loadDAFoam.sh && cd ${{env.DOCKER_WORKING_DIR}}/reg_tests && python run_reg_tests.py"

